[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling configuration
[forms]
  [forms.contact]
    name = "Contact Form"
    fields = [
      { name = "name", type = "text" },
      { name = "email", type = "email" },
      { name = "phone", type = "tel" },
      { name = "message", type = "textarea" },
      { name = "services", type = "text" },
      { name = "roughCarpentry", type = "checkbox" },
      { name = "roofing", type = "checkbox" },
      { name = "siding", type = "checkbox" },
      { name = "deckConstruction", type = "checkbox" },
      { name = "basementFinishing", type = "checkbox" },
      { name = "other", type = "checkbox" }
    ] 